kramdown:
  footnote_backlink: '&#8617;&#65038;'

plugins:
  - jekyll-seo-tag




title: Lauren Mitchell
tagline: Data Analyst with a penchant for AI and Visualization
description: Portfolio and more of Lauren Mitchell, data analyst.
Author: Lauren Mitchell
image: "/img/og-img.png"
lang: en_GB
twitter:
  username: ampinsk
  card: summary
